### ISSUE TITLE
Unable to annotate a model with a custom index

### ISSUE THREAD

**Issue by brightbytes-dude** [ctran/annotate_models#434]
Using `annotate` version 2.7.1 on Rails 5 and Ruby 2.3.3, I have this migration:

```
class ApplicationTables < ActiveRecord::Migration
  def change
    create_table :customers do |t|
      t.with_options(null: false) do |tt|
        tt.string :name
        tt.string :slug
        tt.timestamps
      end
      t.datetime :deleted_at
    end

    execute "CREATE UNIQUE INDEX index_customers_on_lowercase_name ON customers USING btree (lower(name))"
    execute "CREATE UNIQUE INDEX index_customers_on_lowercase_slug ON customers USING btree (lower(slug))"
  end

  .....

end
```

When I run `annotate -ik`, it yields this output, and - as it says - fails to annotate the Customer model:

```
$ annotate -ik
Unable to annotate app/models/customer.rb: undefined method `join' for "lower((name)::text)":String
Did you mean?  JSON
Unable to annotate app/models/customer.rb: no implicit conversion of nil into Array
Model files unchanged.
config/routes.rb unchanged.
```

On Rails 4.2.x, version 2.7.1 of `annotate` when run with the `-i` was unable to generate an annotation for the index, but nonetheless generated an annotation for the fields, which was sufficient.

I have a bunch of other models too, most of which don't have custom indexes, so I don't want to remove index annotation altogether.

Thanks!!

**Comment by samuelgiles** [comment]
It looks like this was fixed but has yet to be released, see here where the column/s are now being coerced into an Array before attempting the `join`: https://github.com/ctran/annotate_models/commit/b5a201d941d571bdb76492f113b2f5fae50e0f9c

I was getting the same error, have switched to using the master branch for the moment until a new release is made:
`gem 'annotate', github: 'ctran/annotate_models', ref: "d108ba8bdec760ded4c8c786b1d7cc72cadba4df"`

**Comment by brightbytes-dude** [comment]
@samuelgiles - That definitely avoids the error - skipping any attempt to annotate the customer indexes - but unfortunately it errs when attempting to annotate routes:

```
Annotated (1): app/models/customer.rb
rake aborted!
ArgumentError: comparison of NilClass with 36 failed
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/annotate/annotate_routes.rb:44:in `each'
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/annotate/annotate_routes.rb:44:in `max'
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/annotate/annotate_routes.rb:44:in `header'
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/annotate/annotate_routes.rb:60:in `do_annotations'
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/tasks/annotate_routes.rake:11:in `block in <top (required)>'
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/tasks/migrate.rake:48:in `update_routes'
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/tasks/migrate.rake:34:in `update_annotations'
/Users/aaron/.rvm/gems/ruby-2.3.3@dpl-cms/bundler/gems/annotate_models-d108ba8bdec7/lib/tasks/migrate.rake:11:in `block (3 levels) in <top (required)>'
```

**Comment by brightbytes-dude** [comment]
OK, this is weird.  After the above error, I commented out what I had in my Gemfile, so it looked like this:

```
  gem 'annotate' # , github: 'ctran/annotate_models', ref: "d108ba8bdec760ded4c8c786b1d7cc72cadba4df"
```

I then re-ran `bundle`, and recreated my app ... and this time, it worked!

Oddly, the `Gemfile.lock` file wasn't changed upon running `bundle`, neither initially when I applied the `:github` and `:ref` keys, nor when I commented them out. 

But, it still works, when it didn't before.  Dunno what's up, but I'm not touching it again until it breaks.  :-)

**Comment by brightbytes-dude** [comment]
Sigh, ignore the last: I couldn't resist playing with it some more.  When I comment-in the selection of the specific `:github` and `:ref`, it does indeed change my `Gemfile.lock` upon `bundle`.  And, it even annotates the indexes correctly:

```
# Indexes
#
#  index_customers_on_lowercase_name  (lower((name)::text)) UNIQUE
#  index_customers_on_lowercase_slug  (lower((slug)::text)) UNIQUE
```

But, it definitely still fails upon attempting to annotate routes.  :-(

Here's my piddly routes file (minus past annotation), if that helps; I've configured my annotate YML file to do the equivalent of `annotate -rp after`, and to occur upon `db:migrate`.

```
Rails.application.routes.draw do
  devise_for :users, ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  root 'admin/dashboard#index'
end
```
